server:
  port: 9092

spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 150MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback/default

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
  instance:
    instance-id: ${spring.application.name}
